// McpTool_ManageAsset.cpp — manage_asset tool definition (114 actions)

#include "McpVersionCompatibility.h"
#include "MCP/McpToolDefinition.h"
#include "MCP/McpToolRegistry.h"
#include "MCP/McpSchemaBuilder.h"
#include "MCP/McpConsolidatedActionRouting.h"

class FMcpTool_ManageAsset : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_asset"); }

	FString GetDescription() const override
	{
		return TEXT("Create, import, duplicate, rename, delete assets. "
			"Edit Material graphs and instances. Analyze dependencies.");
	}

	FString GetCategory() const override { return TEXT("core"); }

	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		return FMcpSchemaBuilder()
			.StringEnum(TEXT("action"), McpConsolidatedActions::ManageAsset(),
				TEXT("Action to perform"))
			.String(TEXT("assetPath"), TEXT("Asset path (e.g., /Game/Path/Asset)."))
			.String(TEXT("directory"), TEXT("Path to a directory."))
			.Array(TEXT("classNames"), TEXT(""))
			.Array(TEXT("packagePaths"), TEXT(""))
			.Bool(TEXT("recursivePaths"), TEXT(""))
			.Bool(TEXT("recursiveClasses"), TEXT(""))
			.Number(TEXT("limit"), TEXT(""))
			.Number(TEXT("offset"), TEXT(""))
			.String(TEXT("sourcePath"), TEXT("Source path for import/move/copy."))
			.String(TEXT("destinationPath"), TEXT("Destination path for move/copy."))
			.Array(TEXT("assetPaths"), TEXT(""))
			.Number(TEXT("lodCount"), TEXT(""))
			.FreeformObject(TEXT("reductionSettings"), TEXT(""))
			.String(TEXT("nodeName"), TEXT("Name identifier."))
			.String(TEXT("eventName"), TEXT("Name of the event."))
			.String(TEXT("memberClass"), TEXT(""))
			.Number(TEXT("posX"), TEXT(""))
			.Number(TEXT("posY"), TEXT(""))
			.String(TEXT("newName"), TEXT("New name for renaming."))
			.Bool(TEXT("overwrite"), TEXT("Overwrite if the asset/file already exists."))
			.Bool(TEXT("save"), TEXT("Save the asset(s) after the operation."))
			.Bool(TEXT("fixupRedirectors"), TEXT(""))
			.String(TEXT("directoryPath"), TEXT("Path to a directory."))
			.String(TEXT("name"), TEXT("Name identifier."))
			.String(TEXT("path"), TEXT("Path to a directory."))
			.String(TEXT("parentMaterial"), TEXT("Material asset path."))
			.FreeformObject(TEXT("parameters"), TEXT(""))
			.Number(TEXT("width"), TEXT(""))
			.Number(TEXT("height"), TEXT(""))
			.String(TEXT("format"), TEXT(""))
			.String(TEXT("meshPath"), TEXT("Mesh asset path."))
			.String(TEXT("tag"), TEXT("Name of the tag."))
			.FreeformObject(TEXT("metadata"), TEXT(""))
			.String(TEXT("graphName"), TEXT("Name of the graph."))
			.String(TEXT("nodeType"), TEXT(""))
			.String(TEXT("nodeId"), TEXT("ID of the node."))
			.String(TEXT("sourceNodeId"), TEXT("ID of the source node."))
			.String(TEXT("targetNodeId"), TEXT("ID of the target node."))
			.String(TEXT("inputName"), TEXT("Name of the pin."))
			.String(TEXT("fromNodeId"), TEXT("ID of the source node."))
			.String(TEXT("fromPin"), TEXT("Name of the source pin."))
			.String(TEXT("toNodeId"), TEXT("ID of the target node."))
			.String(TEXT("toPin"), TEXT("Name of the target pin."))
			.String(TEXT("parameterName"), TEXT("Name of the parameter."))
			.FreeformObject(TEXT("value"), TEXT("Generic value (any type)."))
			.Number(TEXT("x"), TEXT(""))
			.Number(TEXT("y"), TEXT(""))
			.String(TEXT("comment"), TEXT(""))
			.String(TEXT("parentNodeId"), TEXT("ID of the node."))
			.String(TEXT("childNodeId"), TEXT("ID of the node."))
			.Number(TEXT("maxDepth"), TEXT(""))
			.String(TEXT("prefix"), TEXT(""))
			.String(TEXT("suffix"), TEXT(""))
			.String(TEXT("searchText"), TEXT(""))
			.String(TEXT("replaceText"), TEXT(""))
			.Array(TEXT("paths"), TEXT(""))
			.String(TEXT("description"), TEXT(""))
			.Bool(TEXT("checkoutFiles"), TEXT(""))
			.Bool(TEXT("showConfirmation"), TEXT(""))
			.String(TEXT("pinName"), TEXT("Name of the pin."))
			.String(TEXT("desc"), TEXT(""))
			.String(TEXT("materialPath"), TEXT("Material asset path."))
			.String(TEXT("texturePath"), TEXT("Texture asset path."))
			.String(TEXT("expressionClass"), TEXT(""))
			.Number(TEXT("coordinateIndex"), TEXT(""))
			.String(TEXT("parameterType"), TEXT(""))
			.ArrayOfObjects(TEXT("nodes"), TEXT(""))
			.Array(TEXT("tags"), TEXT(""))
			.String(TEXT("folderPath"), TEXT("Path to a directory."))
			.String(TEXT("sourceNode"), TEXT("ID of the source node."))
			.String(TEXT("targetNode"), TEXT("ID of the target node."))
			.String(TEXT("outputPin"), TEXT("Name of the source pin."))
			.String(TEXT("inputPin"), TEXT("Name of the target pin."))
			.String(TEXT("type"), TEXT(""))
			.FreeformObject(TEXT("defaultValue"), TEXT("Generic value (any type)."))
			.String(TEXT("expressionIndex"), TEXT("ID of the node."))
			.Number(TEXT("depth"), TEXT("Texture or render target depth."))
			.Bool(TEXT("force"), TEXT("Force the operation."))
			.Bool(TEXT("recursive"), TEXT("Recurse into child paths."))
			.String(TEXT("reportType"), TEXT("Report type."))
			.String(TEXT("pattern"), TEXT("Pattern to match."))
			.String(TEXT("replacement"), TEXT("Replacement string."))
			.String(TEXT("materialDomain"), TEXT("Material domain."))
			.String(TEXT("blendMode"), TEXT("Blend mode."))
			.String(TEXT("shadingModel"), TEXT("Shading model."))
			.String(TEXT("domain"), TEXT("Material domain alias."))
			.Bool(TEXT("twoSided"), TEXT("Enable two-sided rendering."))
			.Number(TEXT("uTiling"), TEXT("U tiling factor."))
			.Number(TEXT("vTiling"), TEXT("V tiling factor."))
			.String(TEXT("operation"), TEXT("Math operation type."))
			.Number(TEXT("constA"), TEXT("Constant A value."))
			.Number(TEXT("constB"), TEXT("Constant B value."))
			.String(TEXT("code"), TEXT("Code or expression."))
			.String(TEXT("outputType"), TEXT("Output type."))
			.ArrayOfObjects(TEXT("inputs"), TEXT("Input definitions."))
			.ArrayOfObjects(TEXT("additionalOutputs"), TEXT("Additional output definitions."))
			.String(TEXT("group"), TEXT("Group name."))
			.String(TEXT("sourcePin"), TEXT("Source pin name."))
			.String(TEXT("targetPin"), TEXT("Target pin name."))
			.String(TEXT("direction"), TEXT("Traversal direction."))
			.Bool(TEXT("downstream"), TEXT("Traverse downstream connections."))
			.String(TEXT("startNodeId"), TEXT("Start node ID."))
			.String(TEXT("endPin"), TEXT("End pin name."))
			.Bool(TEXT("orphansOnly"), TEXT("Only include orphaned nodes."))
			.String(TEXT("functionPath"), TEXT("Material function asset path."))
			.String(TEXT("inputType"), TEXT("Input type."))
			.String(TEXT("instancePath"), TEXT("Material instance asset path."))
			.String(TEXT("layerName"), TEXT("Layer name."))
			.String(TEXT("blendType"), TEXT("Blend type."))
			.ArrayOfObjects(TEXT("layers"), TEXT("Layer configurations."))
			.Array(TEXT("nodeIds"), TEXT("Node IDs."))
			.String(TEXT("sourceTexture"), TEXT("Source texture path."))
			.Number(TEXT("strength"), TEXT("Strength value."))
			.Number(TEXT("scale"), TEXT("Scale value."))
			.Number(TEXT("octaves"), TEXT("Octave count."))
			.Number(TEXT("samples"), TEXT("Sample count."))
			.Number(TEXT("newWidth"), TEXT("New width."))
			.Number(TEXT("newHeight"), TEXT("New height."))
			.String(TEXT("filterMethod"), TEXT("Filter method."))
			.Number(TEXT("inBlack"), TEXT("Input black point."))
			.Number(TEXT("inWhite"), TEXT("Input white point."))
			.Number(TEXT("gamma"), TEXT("Gamma value."))
			.ArrayOfObjects(TEXT("curvePoints"), TEXT("Curve control points."))
			.Number(TEXT("amount"), TEXT("Effect amount."))
			.Number(TEXT("radius"), TEXT("Radius value."))
			.String(TEXT("channel"), TEXT("Channel name."))
			.String(TEXT("redTexture"), TEXT("Red channel texture path."))
			.String(TEXT("greenTexture"), TEXT("Green channel texture path."))
			.String(TEXT("blueTexture"), TEXT("Blue channel texture path."))
			.String(TEXT("baseTexture"), TEXT("Base texture path."))
			.String(TEXT("blendTexture"), TEXT("Blend texture path."))
			.Number(TEXT("opacity"), TEXT("Opacity value."))
			.String(TEXT("compressionSettings"), TEXT("Texture compression settings."))
			.String(TEXT("textureGroup"), TEXT("Texture group."))
			.Number(TEXT("lodBias"), TEXT("LOD bias."))
			.Bool(TEXT("virtualTextureStreaming"), TEXT("Enable virtual texture streaming."))
			.Bool(TEXT("neverStream"), TEXT("Never stream this texture."))
			.Number(TEXT("streamingPriority"), TEXT("Streaming priority."))
			.Number(TEXT("speed"), TEXT("Speed value."))
			.Number(TEXT("speedX"), TEXT("X speed value."))
			.Number(TEXT("speedY"), TEXT("Y speed value."))
			.Number(TEXT("levels"), TEXT("Level count."))
			.Required({TEXT("action")})
			.Build();
	}
};

MCP_REGISTER_TOOL(FMcpTool_ManageAsset);
